name: iot
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  mqtt_client: ^10.0.0
  pull_to_refresh_flutter3: ^2.0.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_flutter: ^1.10.25
  timezone: ^0.9.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/susdog.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/rick-roll.gif
